title: Genetic and Density studies of felids
description: This repository features the data summary and map of genetic diversity and population density (camera-trap) studies of felids
theme: jekyll-theme-slate
