png(filename="Figures/boxplot_out_clus.png",width=10,height=11,units="in",res=300)
layout(matrix(c(1,2,3,4), ncol=1, byrow=TRUE), heights=c(1.2, 1.2, 1.2, 1.7))
par(mai=c(0.2,0.7,0.3,0.2), cex.lab=1.5)
boxplot(gen_clus$DP_log~gen_clus$sp,  xaxt="n", xlab=NA,  ylab="log10(PD)", cex=2, col=no_green[names(no_green) %in% levels(gen_clus$sp)],)
abline(h=mean(gen_clus$DP_log), lty="dashed")
mtext("a)", side=3, line=1, adj=0)
par(mai=c(0.2,0.7,0,0.2), cex.lab=1.5)
boxplot(gen_clus$ho~gen_clus$sp,  xaxt="n", xlab=NA,  ylab="Ho", cex=2, col=no_green[names(no_green) %in% levels(gen_clus$sp)])
abline(h=mean(gen_clus$ho, na.rm=T), lty="dashed")
par(mai=c(0.2,0.7,0,0.2), cex.lab=1.5)
boxplot(gen_clus$he~gen_clus$sp, las=2, xlab=NA,  ylab="He", xaxt="n", cex=2, col=no_green[names(no_green) %in% levels(gen_clus$sp)])
abline(h=mean(gen_clus$he, na.rm=T), lty="dashed")
par(mai=c(1.2,0.7,0,0.2), cex.lab=1.5)
boxplot(log10(gen_clus$n.allele)~gen_clus$sp, las=2, xlab=NA,  ylab="log10(AR)",cex=2, col=no_green[names(no_green) %in% levels(gen_clus$sp)])
abline(h=log10(mean(gen_clus$n.allele,na.rm=T)), lty="dashed")
dev.off()


png(filename="Figures/boxplot_out_count.png",width=10,height=10,units="in",res=300)
layout(matrix(c(1,2,3,4), ncol=1, byrow=TRUE), heights=c(1.2, 1.2, 1.2, 1.7))
par(mai=c(0.2,0.7,0.3,0.2), cex.lab=1.5)
boxplot(gen_count$DP_log~gen_count$sp,  xaxt="n", xlab=NA,  ylab="log10(PD)", cex=2, col=no_green[names(no_green) %in% levels(gen_count$sp)])
abline(h=mean(gen_count$DP_log, na.rm=T), lty="dashed")
mtext("b)", side=3, line=1, adj=0)
par(mai=c(0.2,0.7,0,0.2), cex.lab=1.5)
boxplot(gen_count$ho~gen_count$sp,  xaxt="n", xlab=NA,  ylab="Ho", cex=2, col=no_green[names(no_green) %in% levels(gen_count$sp)])
abline(h=mean(gen_count$ho, na.rm=T), lty="dashed")
par(mai=c(0.2,0.7,0,0.2), cex.lab=1.5)
boxplot(gen_count$he~gen_count$sp, las=2, xlab=NA,  ylab="He", xaxt="n", cex=2, col=no_green[names(no_green) %in% levels(gen_count$sp)])
abline(h=mean(gen_count$he, na.rm=T), lty="dashed")
par(mai=c(1.2,0.7,0,0.2), cex.lab=1.5)
boxplot(log10(gen_count$n.allele)~gen_count$sp, las=2, xlab=NA,  ylab="log10(AR)",cex=2, col=no_green[names(no_green) %in% levels(gen_count$sp)])
abline(h=log10(mean(gen_count$n.allele, na.rm=T)), lty="dashed")
dev.off()


png(filename="Figures/boxplot_sampl_clus.png",width=10,height=12,units="in",res=300)
layout(matrix(c(1,2,3,4), ncol=1, byrow=TRUE), heights=c(0.9, 0.9, 0.9, 1.3))
par(mai=c(0.2,0.7,0.3,0.2), cex.lab=1.5)
boxplot(log10(gen_clus$sample.size)~gen_clus$sp,   xaxt="n", cex=1.5, xlab=NA, las=2, 
        col=no_green[names(no_green) %in% unique(gen_clus$sp)], ylab="log10(sample size)")
abline(h=mean(log10(gen_clus$sample.size), na.rm=T), lty=2)
mtext("A)", side=3, line=1, adj=0)

par(mai=c(0.2,0.7,0,0.2), cex.lab=1.5)
boxplot(gen_clus$no.of.loci~gen_clus$sp, xaxt="n", col=no_green[names(no_green) %in% unique(gen_clus$sp)] , xlab=NA,  cex=1.5, las=2, ylab="No. of loci")
abline(h=mean(gen_clus$no.of.loci, na.rm=T), lty=2)


par(mai=c(0.2,0.7,0.1,0.2), cex.lab=1.5)
boxplot(log10(gen_count$sample.size) ~gen_count$sp, xaxt="n", cex=1.5, xlab=NA, las=2, col=no_green[names(no_green) %in% unique(gen_count$sp)], ylab="log10(sample size)")
abline(h=mean(log10(gen_count$sample.size), na.rm=T), lty=2)

mtext("B)", side=3, line=0, adj=0)

par(mai=c(1.3,0.7,0,0.2), cex.lab=1.5, cex.axis=1.2)
boxplot(gen_count$no.of.loci~gen_count$sp, col=no_green[names(no_green) %in% unique(gen_count$sp)] , xlab=NA,  cex=1.5, las=3, ylab="No. of loci")
abline(h=mean(gen_count$no.of.loci, na.rm=T), lty=2)
dev.off()


png(filename="Figures/boxplot_out_count_newdata.png",width=10,height=10,units="in",res=300)
layout(matrix(c(1,2,3,4), ncol=1, byrow=TRUE), heights=c(1.2, 1.2, 1.2, 1.7))
par(mai=c(0.2,0.7,0.3,0.2), cex.lab=1.5)
boxplot(clus$DP_log~clus$sp,  xaxt="n", xlab=NA,  ylab="log10(PD)", cex=2,  na.action=na.omit, col=no_green[names(no_green) %in% levels(gen_count$sp)])
abline(h=mean(clus$DP_log, na.rm=T), lty="dashed")
mtext("b)", side=3, line=1, adj=0)
par(mai=c(0.2,0.7,0,0.2), cex.lab=1.5)
boxplot(clus$ho~clus$sp,  xaxt="n", xlab=NA,  ylab="Ho", cex=2,  na.action=na.omit, col=no_green[names(no_green) %in% levels(gen_count$sp)])
abline(h=mean(clus$ho, na.rm=T), lty="dashed")
par(mai=c(0.2,0.7,0,0.2), cex.lab=1.5)
boxplot(clus$he~clus$sp, las=2, xlab=NA,  ylab="He", xaxt="n",  na.action=na.omit, cex=2, col=no_green[names(no_green) %in% levels(gen_count$sp)])
abline(h=mean(clus$he, na.rm=T), lty="dashed")
par(mai=c(1.2,0.7,0,0.2), cex.lab=1.5)
boxplot(log10(clus$n.allele)~clus$sp, las=2, xlab=NA,  ylab="log10(AR)",cex=2,  na.action=na.omit, col=no_green[names(no_green) %in% levels(gen_count$sp)])
abline(h=log10(mean(clus$n.allele, na.rm=T)), lty="dashed")
dev.off()